config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }

  resources :rooms do
    member do
      get :reserve
    end
  end
  ##resources :rooms
  #ruta de inicio dirije al cotrolador pagina y accion home
  root to: "rooms#index"

  get "home", to: 'pages#home'
  get "about", to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hotel.rb
class Hotel < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
  mount_uploader :image, RoomUploader
  belongs_to :hotel

  validates :length,
            :width,
            :description,
            :hotel_id,
            :image,
            presence: true

  validates :length, :width, numericality: { only_float: true}
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   include DeviseWhitelist
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
    extend ActiveSupport::Concern

    included do
        before_action :configure_permitted_parameters, if: :devise_controller?
    end

    private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all
    before_action :set_room, only: [:show, :edit, :destroy, :reserve]

    def index
        @rooms = Room.all
    end

    def show
    end

    def new
        @room = Room.new
    end

    def create
        @room = Room.new(room_params)

        respond_to do |format|
            if @room.save
                format.html { redirect_to rooms_path,
                    notice: 'Room creado correctamente' }
                else
                    format.html { render :new }
            end
        end
    end

    def edit
        
    end

    def update
        @room = Room.find(params[:id])

        respond_to do |format|
            if @room.update(room_params)
                format.html { redirect_to rooms_path,
                    notice: 'Room actualizado correctamente'}
            else
            format.html { render :edit }
            end
        end
    end

    def destroy
        @room.destroy

        respond_to do |format|
        format.html { redirect_to rooms_url,
                    notice: 'Habitación eliminada' }
        end
    end

    def reserve
        @room.update(taken: true)
        redirect_to rooms_url, notice: 'Habitación apartada'
    end

    private
    def set_room
    @room = Room.find(params[:id])
    end

    def room_params
        params.require(:room).permit(:id,
                                    :length,
                                    :width, 
                                    :image, 
                                    :hotel_id,
                                    :taken, 
                                    :description)
                             .with_defaults(hotel_id: 1,
                                        image: "http://placehold.it/700x400",
                                        taken: 0)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

   <body>
    <%= render 'shared/navbar' %>
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="cover-heading">About</div>
  <hr>

  <div class="row">
    <div class="col-md-6 my-auto">
      <h3>Dirección</h3>
      <p>Citilcum, Izamal, Yucatán</p>

      <p>Número de teléfono</p>
      <p>+52 9999902926</p>

      <h3>Email</h3>
      <p> <a href="mailto:dannyoxte@gmail.com?subject=Contacto" "email me">Email me</a></p>
    </div>

    <div class="col-md-6">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14904.172926865149!2d-89.11821834999999!3d20.95077895!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8f5698f6787ac0c3%3A0x645b9ac9ed6fad56!2sCitilcum%2C%20Yuc.!5e0!3m2!1ses-419!2smx!4v1676843493926!5m2!1ses-419!2smx" width="450" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved: %></h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :Largo %>
        <%= form.text_field :length, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :Ancho %>
        <%= form.text_field :width, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Imagen <%= form.file_field :image, style: 'display:none' %>
        </label>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :Descripción %>
        <%= form.text_area :description, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= form.submit 'Guardar', class: 'btn btn-primary btn-block' %>
      </div>
    </div>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<div class="container">
  <h1>Editar habitación</h1>

  <%= render 'form', room: @room %>
</div>

app/views/rooms/index.html.erb
<main role="main">
    <section class="jumbotron text-center">
        <div class="container">
          <h1>¡Bienvenido!</h1>
             <p class="lead text-muted">
            En esta página podrás encontrar todas nuestras habitaciones disponibles. Si estás interesado en alguna, ¡solo basta con dar click en <strong>Apartar</strong>
             </p>
        </div>
    </section>

 <div class="album py-5 bg-light">
   <div class="container">
     <% if logged_in?(:site_admin) %>
       <div class="text-center my-3">
          <%= link_to 'Crear habitación', new_room_path, class: 'btn btn-primary' %>
       </div>
     <% end %>
     <div class="row">
       <% @rooms.each do |room| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm text-center">
            <%= image_tag (room.image).to_s %>
            <div class="card-body">
               <p class="card-text">
                  <%= room.description.split(" ").first(15).join(" ") %>
               </p>
               <%= link_to 'Detalles', room_path(room), class: 'btn btn-warning' %>
               <% if !room.taken %>
                  <%= link_to 'Apartar', reserve_room_path(room), class: 'btn btn-success' %>
                <% end %>
               <!--<a href="#" class="btn btn-primary ml-4">Apartar</a>-->
            </div>
          </div>
        </div>
       <% end %>
     </div>
   </div>
 </div>
</main>

app/views/rooms/new.html.erb
<div class="container my-5">
  <div class="col">
    <h1>Nueva habitación</h1>

    <%= render 'form', room: @room %>
    <%= link_to 'Volver', rooms_path %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-7">
            <%= image_tag (@room.image).to_s, style: 'width:100%;' %>
        </div>
        <div class="col-md-5">
            <p><%= @room.description %></p>
            <p>Largo: <%= @room.length %></p>
            <p>Ancho: <%= @room.width %></p>
            <% if !@room.taken %>
                <%= link_to 'Apartar', reserve_room_path(@room), class: 'my-3 btn btn-success' %>
            <% end %>

            <!--<a href="#" class="btn btn-primary my-3">Apartar</a>-->
            <% if logged_in?(:site_admin) %>
                <div>
                <%= link_to 'Editar', edit_room_path(@room), class: 'btn btn-warning' %>
                <!--<%= link_to 'Eliminar', @room, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger' %>-->
                <%= link_to "Eliminar", @room, data: { turbo_method: :delete, confirm:'¿Estás seguro?' }, class:'btn btn-danger' %>
                </div>
            <% end %>
        </div>
    </div>
    <div class="row">
        <%= link_to 'Regresar', rooms_path, class: "btn btn-secondary my-3" %>
    </div>
</div>

app/views/shared/_navbar.html.erb
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'Home', rooms_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'About', about_path, class:"nav-link"%>
            </li>
            
               <% if current_user %>
               <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class:"nav-link" %>
               <% else %>
               <%= link_to "Register", new_user_registration_path, class:"nav-link" %>
               <%= link_to "login", new_user_session_path, class:"nav-link" %>
               <% end %>
            
           
            
          </ul>
         
        </div>

      </div>
    </nav>